// 90% generated by ChatGPT
// https://chatgpt.com/share/67191d84-87d4-800c-826a-63a1bb41fa6e

import { useState, useEffect } from "react";

const cardList = () => {
  const [dscCards, setDscCards] = useState([]);

  useEffect(() => {
    const images = import.meta.glob("../../assets/dsc/*.jpg");
    let cardList = [];
    let index = 0;

    // Fetch all image paths and build card list
    const loadImages = async () => {
      for (const path in images) {
        await images[path](); // Wait for each image to be imported
        // Vite serves assets in the src/assets folder as /src/assets/
        const publicPath = path.replace("../../assets", "/src/assets");
        const fileName = publicPath.replace("/src/assets/dsc/", '')
        const cardTitle = fileName.replace(/_/g, " ").replace(".jpg", "")

        cardList.push({
          image: publicPath, // Now it points to the correct URL
          title: cardTitle,
          id: index,
        });
        index += 1;
      }

      // Update state once all images are loaded
      setDscCards(cardList);
    };

    loadImages(); // Trigger the async loading function
  }, []); // Empty dependency array ensures this runs only once on mount

  return (
    <>
      {dscCards.map((card) => (
        <div className="card" key={card.id}>
          <img src={card.image} alt={`Card ${card.id}`} />
          <span>Title: {card.title}</span>
          <span>Set: dsc</span>
        </div>
      ))}
    </>
  );
};

export default cardList;
